services:
  users-database:
    container_name: users-database
    ports:
      - "5432:5432"
    extends:
      file: compose-common-config.yml
      service: microservice-database-config
  orders-database:
    container_name: orders-database
    ports:
      - "5433:5432"
    extends:
      file: compose-common-config.yml
      service: microservice-database-config
  accounts-database:
    container_name: accounts-db
    ports:
      - "5434:5432"
    extends:
      file: compose-common-config.yml
      service: microservice-database-config

networks:
  artem:
    driver: "bridge"