services:
  network-deploy-service:
    networks:
      - artem
  microservice-database-config:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      MYSQL_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ../.env
    extends:
      service: network-deploy-service