server:
  port: 8082
spring:
  application:
    name: "order"
  profiles:
    active: "default"
  config:
    import:
      - "optional:file:../.env[.properties]"
      - "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%level] [%logger{20}] - %msg%n"
