server:
  port: 8082
spring:
  application:
    name: "waybill"
  profiles:
    active: "default"
  config:
    import:
      - "optional:file:../.env[.properties]"
      - "optional:configserver:http://localhost:8071/"
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%level] [%logger{20}] - %msg%n"
