server:
  port: 8083
spring:
  application:
    name: "account-management"
  profiles:
    active: "default"
  config:
    import:
      - "optional:file:../.env[.properties]"
      - "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%level] [%logger{20}] - %msg%n"
